# Cloudflare Workers deployment configuration for SPA
name = "the-innovation-curve"
main = "worker-backend.js"
compatibility_date = "2025-08-08"

# SPA Assets configuration
[assets]
directory = "./dist/"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = [
  "/api/*",           # All API routes go to Worker first
  "/sitemap.xml",     # Sitemap route goes to Worker first
  "/auth/callback",   # Authentication callback goes to Worker
  "!/api/docs/*"      # Exclude API docs (if you add them later)
]

# Frontend build configuration
[build]
command = "npm run build"
publish = "dist"

[vars]
# Frontend environment variables
VITE_API_URL = "https://web-builder-five-rust.vercel.app/api"

[env.development]
[env.development.vars]
VITE_API_URL = "http://localhost:3000/api"
