# Cloudflare Pages deployment configuration for frontend only
name = "the-innovation-curve"
compatibility_date = "2025-08-07"

# Remove the main entry point since we're deploying the frontend
# main = "server/api/index.js"  # Commented out

# Frontend build configuration
[build]
command = "npm run build"
publish = "dist"

[vars]
# Only frontend environment variables
VITE_API_URL = "https://web-builder-five-rust.vercel.app/api"

[env.development]
[env.development.vars]
VITE_API_URL = "http://localhost:3000/api"
