# Cloudflare Workers deployment configuration
name = "web-builder-blog-api"
main = "src/index.js"
compatibility_date = "2023-08-07"

[env.production.vars]
NODE_ENV = "production"
JWT_SECRET = "your-production-jwt-secret-here"
ADMIN_EMAIL = "admin@theinnovationcurve.com"

[[env.production.d1_databases]]
binding = "DB"
database_name = "blog-database"
database_id = "your-d1-database-id"

[env.development]
[env.development.vars]
NODE_ENV = "development"
